// add the following line and replace necessary values if you are not loading the library implicitly
@Library('kna-skX-jenkins-shared-library') _

pipeline {
    agent any

    options {
        timestamps()
    }
//    environment {
//        //Use Pipeline Utility Steps plugin to read information from pom.xml into env variables
//        IMAGE = readMavenPom().getArtifactId()
//       VERSION = readMavenPom().getVersion()
//    }

    stages {
//        stage('qa') {
//            steps {
//                mvn_qa
//            }
//        }
        stage('build') {
            steps {
                mvn_build
                    settingsPath: "settings.xml",
                     pomPath: "pom.xml"
            }
        }
    }
    post {
        failure {
//            // notify users when the Pipeline fails
//            mail
//                to: 'c3did@kairops.online',
//                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
//                body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}